### ISSUE TITLE
Heroku setup

### ISSUE THREAD

**Issue by krainboltgreene** [dondurrance/tracker#5]
If you're going to use Heroku (and you should, really) you need to do the following:

In the `Gemfile`:

``` ruby
group :development, :test do
  gem "sqlite3"
end

group :development do
  gem "heroku"
end

group :production do
  gem "pg"
end
```

In the `config/database.yml`:

``` yaml
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: tracker_production
  pool: 5
  username: tracker
  password:

```

This way you get to use Heroku's PGSQL, but still have the simplicity of SQLite in testing and development modes.
